# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'second_window22.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow1(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color: rgb(85, 85, 127);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.student_table = QtWidgets.QTableWidget(self.centralwidget)
        self.student_table.setGeometry(QtCore.QRect(240, 110, 525, 455))
        self.student_table.setStyleSheet("background-color: rgb(255, 221, 172);")
        self.student_table.setObjectName("student_table")
        self.student_table.setColumnCount(0)
        self.student_table.setRowCount(0)
        self.student_table.setStyleSheet("/* цвет заголовков столбцов и строк */\n"
                                     "QHeaderView::section {\n"
                                     "    background-color: rgb(153, 72, 87);\n"
                                     "    color: rgb(255, 221, 172)\n"
                                     "}\n"
                                     "\n"
                                     "/* цвет ячейки слева вверху*/\n"
                                     "QTableCornerButton::section {\n"
                                     "    background-color: rgb(153, 72, 87)\n"
                                     "}\n"
                                     "\n"
                                     "/* цвет ячеек с значениями */\n"
                                     "QTableWidget::item {\n"
                                     "    background-color: rgb(255, 221, 172);\n"
                                     "    color: rgb(31, 31, 147);\n"
                                     "}")
        self.exit_button = QtWidgets.QPushButton(self.centralwidget)
        self.exit_button.setGeometry(QtCore.QRect(60, 500, 121, 31))
        self.exit_button.setStyleSheet("background-color: rgb(153, 72, 87);\n"
"color: rgb(255, 221, 172);")
        self.exit_button.setObjectName("exit_button")
        self.save_button = QtWidgets.QPushButton(self.centralwidget)
        self.save_button.setGeometry(QtCore.QRect(60, 430, 121, 31))
        self.save_button.setStyleSheet("background-color: rgb(153, 72, 87);\n"
"color: rgb(255, 221, 172);")
        self.save_button.setObjectName("save_button")
        self.enter_label = QtWidgets.QLabel(self.centralwidget)
        self.enter_label.setGeometry(QtCore.QRect(248, 30, 511, 51))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(20)
        self.enter_label.setFont(font)
        self.enter_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.enter_label.setStyleSheet("color: rgb(255, 221, 172);")
        self.enter_label.setAlignment(QtCore.Qt.AlignCenter)
        self.enter_label.setObjectName("enter_label")
        self.fullname = QtWidgets.QLabel(self.centralwidget)
        self.fullname.setGeometry(QtCore.QRect(24, 120, 201, 21))
        self.fullname.setStyleSheet("color: rgb(255, 221, 172);")
        self.fullname.setObjectName("fullname")
        self.group = QtWidgets.QLabel(self.centralwidget)
        self.group.setGeometry(QtCore.QRect(20, 190, 201, 21))
        self.group.setStyleSheet("color: rgb(255, 221, 172);")
        self.group.setObjectName("group")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(70, 380, 113, 22))
        self.lineEdit.setStyleSheet("background-color: rgb(255, 221, 172);")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(70, 320, 113, 22))
        self.lineEdit_2.setStyleSheet("background-color: rgb(255, 221, 172);")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.fullname_2 = QtWidgets.QLabel(self.centralwidget)
        self.fullname_2.setGeometry(QtCore.QRect(20, 350, 201, 21))
        self.fullname_2.setStyleSheet("color: rgb(255, 221, 172);")
        self.fullname_2.setObjectName("fullname_2")
        self.fullname_3 = QtWidgets.QLabel(self.centralwidget)
        self.fullname_3.setGeometry(QtCore.QRect(20, 290, 201, 21))
        self.fullname_3.setStyleSheet("color: rgb(255, 221, 172);")
        self.fullname_3.setObjectName("fullname_3")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Электронный дневник"))
        self.exit_button.setText(_translate("MainWindow", "Выйти"))
        self.save_button.setText(_translate("MainWindow", "Изменить пароль"))
        self.enter_label.setText(_translate("MainWindow", " Электронный дневник"))
        self.fullname.setText(_translate("MainWindow", "TextLabel"))
        self.group.setText(_translate("MainWindow", "TextLabel"))
        self.fullname_2.setText(_translate("MainWindow", "               Новый пароль:"))
        self.fullname_3.setText(_translate("MainWindow", "               Старый пароль:"))
